FROM node:boron

# Create Application Directory
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
 
# Bundle app source
COPY . /usr/src/app

# Start the beast
#EXPOSE 8080 
CMD ["npm", "start"]

